
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: keyboard_cat
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -c 'select * from games;'"]
    ports:
      - 5432:5432
